// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/mock_shortener_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockshortenerService is a mock of shortenerService interface.
type MockshortenerService struct {
	ctrl     *gomock.Controller
	recorder *MockshortenerServiceMockRecorder
	isgomock struct{}
}

// MockshortenerServiceMockRecorder is the mock recorder for MockshortenerService.
type MockshortenerServiceMockRecorder struct {
	mock *MockshortenerService
}

// NewMockshortenerService creates a new mock instance.
func NewMockshortenerService(ctrl *gomock.Controller) *MockshortenerService {
	mock := &MockshortenerService{ctrl: ctrl}
	mock.recorder = &MockshortenerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockshortenerService) EXPECT() *MockshortenerServiceMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockshortenerService) Resolve(id string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockshortenerServiceMockRecorder) Resolve(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockshortenerService)(nil).Resolve), id)
}

// Shorten mocks base method.
func (m *MockshortenerService) Shorten(url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shorten", url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Shorten indicates an expected call of Shorten.
func (mr *MockshortenerServiceMockRecorder) Shorten(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shorten", reflect.TypeOf((*MockshortenerService)(nil).Shorten), url)
}
